name: 'generate-new-repo'
description: 'Creates new repository at location specified for IETF Drafts'

inputs:
  draft-name:
    description: 'Name of new draft and repository'
    required: true
  org-name:
    description: 'Name of Github Organization to use'
  create-repo-token-username:
    description: 'Github username for create-repo-github-token'
    required: true
  create-repo-github-token:
    description: 'Github token for creating repositories'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.draft-name }}
    - ${{ inputs.create-repo-token-username }}
    - ${{ inputs.create-repo-github-token }}
    - ${{ inputs.org-name }}
