name: 'generate-new-repo'
description: 'Creates new repository at location specified for IETF Drafts'

inputs:
  draft-name:
    description: 'Name of new draft and repository'
    required: true
  org-name:
    description: 'Name of Github Organization to use'
  create-repo-token-username:
    description: 'Github username for create-repo-github-token'
    required: true
  create-repo-github-token:
    description: 'Github token for creating repositories'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Create repo"
      id: create
      shell: bash
      env:
        DRAFT_NAME: ${{ inputs.draft-name }}
        ORG_NAME: ${{ inputs.org-name }}
        CREATE_REPO_GITHUB_TOKEN: ${{ inputs.create-repo-github-token }}
        TOKEN_USER: ${{ inputs.create-repo-token-username }}
      run: |
        echo "Creating new repository ${DRAFT_NAME}"
        mkdir /home/runner/work/"${DRAFT_NAME}"
        cp Makefile /home/runner/work"${DRAFT_NAME}"

        # change api url based on whether an org name was provided
        if [[ -z "${ORG_NAME}" ]]; then
            repository_prefix="user"
        else
            repository_prefix="orgs/${ORG_NAME}"
        fi

        resp=$(curl -s \
            -u "${TOKEN_USER}:${CREATE_REPO_GITHUB_TOKEN}" \
            -o response.txt \
            -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/"${repository_prefix}"/repos \
            -d '{"name":"'${DRAFT_NAME}'"}')

        if [[ "$resp" != "201" ]]; then
          echo "Response $resp received from GitHub API, please check token permissions."
          exit 1
        else
          rm response.txt
          echo "Repository ${repository_prefix}/${DRAFT_NAME} created."
          echo "git_url=$(cat response.txt | jq -r '.clone_url')" >> $GITHUB_ENV
          cd /home/runner/work/"${DRAFT_NAME}"
          git init
          git checkout -b main
          git remote add origin "$git_url"
          sed -i 's/REPLACE_DRAFT_NAME/'"${DRAFT_NAME}"'/g' Makefile
          git add .
          git commit -m "initial commit"
          git push --set-upstream origin main
          echo "Created new repository ${DRAFT_NAME}"
        fi
