name: 'generate-new-repo'
description: 'Creates new repository at location specified for IETF Drafts'

inputs:
  draft-name:
    description: 'Name of new draft and repository'
    required: true
  org-name:
    description: 'Name of Github Organization to use'
  create-repo-github-user:
    description: 'Github username for create-repo-github-token'
    required: true
  create-repo-github-token:
    description: 'Github token for creating repositories'
    required: true
  private-repo:
    description: 'Whether to create as a private repo (default false)'
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.draft-name }}
    - ${{ inputs.create-repo-github-user }}
    - ${{ inputs.create-repo-github-token }}
    - ${{ inputs.org-name }}
    - ${{ github.actor }}
    - ${{ inputs.private-repo }}
