name: 'validate-markdown'
on:
  push:
    paths:
      - 'draft-*.md'
    branches-ignore:
      - 'main'
  pull_request:
    paths:
      - 'draft-*.md'

jobs:
  generate-draft:
    runs-on: ubuntu-latest
    name: Generate all versions of the current IETF draft
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Install needed tools
        id: install
        run: |
          sudo apt-get install -y --no-install-recommends \
            ruby-kramdown-rfc2629 \
            xml2rfc

      - name: Validate current draft
        id: validate-draft
        run: make
