name: 'Generate new repo'
on:
  workflow_dispatch:
    inputs:
      draft-name:
        required: true
        description: 'Name of new draft and repository'
      token-username:
        description: 'Github username for CREATE_REPO_GITHUB_TOKEN'
        required: true
      org-name:
        description: 'Name of Github Organization to use'

jobs:
  generate-new-repository:
    runs-on: ubuntu-latest
    name: Create a new IETF draft repository
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Create new repository action
        id: generate-repo
        uses: ./ # Uses an action in the root directory
        with:
          draft-name: ${{ github.event.inputs.draft-name }}
          org-name: ${{ github.event.inputs.org-name }}
          token-username: ${{ github.event.inputs.token-username }}
